const path = require('path');

module.exports = {
  // This file usually imports all other modules in your application
  entry: './src/index.js',
  output: {
    // This is the file that will be generated by webpack as a result of the build process
    filename: 'bundle.js',

    // This is the directory where the generated file will be placed
    path: path.resolve(__dirname, './dist'),
  },
  // This is the mode that webpack will run in (Ex: development, production)
  mode: 'none',
};
